### ISSUE TITLE
Request for nested lists

### ISSUE THREAD

**Issue by markduk** [ChrisMayor/D365RichTextEditor#12]
Hi
Thanks for your awesome Rich Text Editor, our users are enjoying it's simplicity.  They have requested however, would it be possible to have nested lists?

e.g.

1. Item1
2. Item2
     - Item2.1
     - Item2.2
3. Item3

Thanks

**Comment by ChrisMayor** [comment]
Hello Mark,

thank you for submitting your question.

Great to hear, that your users enjoying the Rich Text Editor.

The underlying editor quill, unfortunately, does not support this kind of nested list.

In the latest version of quill I'm only able to get this (wrong) output when trying to create a nested list by use of 2 lists:

1. Item 1
2. Item 2
* Item 2.1 
* Item 2.2
1. Item 3

So the numbering of Item 3 starting at 1 again.

It would be possible to add indent icons to the toolbar to produce the numbered list by self numbering the items, those indent icons are currently not added to the editor by me.

Maybe try this in the react-quill demo https://zenoamaro.github.io/react-quill/ and let me know if this workaround is sufficient for you, then I will try to add those icons to the toolbar.

Christoph

**Comment by ChrisMayor** [comment]
Closed due to inactivity
