### ISSUE TITLE
Characters disappearing while entering text

### ISSUE THREAD

**Issue by tylersand** [ChrisMayor/D365RichTextEditor#2]
I am noticing an issue where characters disappear while typing.  In the linked video, you will see that at around the 24 second mark, I enter the word "woman" and it changes it to "womn".  I have seen this happen with alphanumeric characters and spaces, on multiple machines, and it gets worse the faster you type.  It seems like perhaps an issue with the events for update view and text changed, where asynchronously the value in the text box is getting changed back to what it was milliseconds ago.

https://tylereriksandllc-my.sharepoint.com/:v:/g/personal/tyler_ts_solutions/EZen5YnTB7ZHpCMY-qa50PwBaLcxDiSrK7pijkH6qNzCJA?e=ddCZZO

**Comment by jellevervloessem** [comment]
Same here. Maybe it has some thing to do withbautosave....
Whe the characters disappear the changed fields on the form are lost too.

**Comment by ChrisMayor** [comment]
Hello,
will have a look at the issue in the next days.  Unfortunately, the issue doesn't appear on the PowerApps component framework Test Environment. I think too, that it is probably related to autosave in Dynamics:

When the updateView method is called by Dynamics, the control has to check if the field was changed in Dynamics and in this case has to update the control. I think the root issue is related to the PCF Framework implementation and/or Dynamics and autosave.

I will check in the next days if there is a workaround.

**Comment by tylersand** [comment]
Here's some information that I found that is likely the same issue.  The best workaround that this group came up with was to check the field value in updateView() and ignore it if it is the old value.  Hopefully this helps.

https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Which-event-for-notifyOutputChanged/td-p/481721

**Comment by ChrisMayor** [comment]
I fixed the issue now with some small changes in the code.

To get the changes reflected in Dynamics you have to completely uninstall the current solution. Unfortunately in the previous version, I didn't change the default behavior for PCF controls and I created an unmanaged solution and if you leave the previous version in dynamics, the changed will not be reflected :-(

Now from the current version, I will always generate a managed solution, this will ensure, that changes in the next versions will be reflected if you update the solution.

Please follow the update instructions "Update instructions V1.0 -> V2.0" in the readme.md on the main page.
