### ISSUE TITLE
Control doesn't behave like other built-in controls

### ISSUE THREAD

**Issue by Triangle333** [ChrisMayor/D365RichTextEditor#4]
1. Control doesn't respect "Number of Rows" setting (Formatting tab) and its height grows with content. Minor issue and I understand that this is probably impossible to implement...
2. Control doesn't support disabling. **BIG** issue, especially for Inactive records (it is still possible to change & save data in this control even if the entire form is disabled). PCF supports this - please implement.

**Comment by ChrisMayor** [comment]
Hello,
I will have a look at this in the next days.

**Comment by walkerjono** [comment]
> Control doesn't respect "Number of Rows" setting (Formatting tab) and its height grows with content. Minor issue and I understand that this is probably impossible to implement...

It would be great to be able to set a min-height for the control and for it to auto expand if the content is longer than the min-height

**Comment by ChrisMayor** [comment]
Hello,

1) I added the suggestion from walterjono now with version 2.1 it is now possible to enter parameters "height, min-height, max-height" in pixels at the customizing of the control. If no values are entered the control will size to 200px by default. Now the control behaves like other dynamics controls. I will document this in the readme.md later.

2) Is in parts now implemented, if you open a deactivated form the control is deactivated. But if you deactivate the current form without reopening it currently not works in 2.1 ... I will now have a look at it and will fix this now

**Comment by ChrisMayor** [comment]
Thank you for your suggestions and issues.

I was able to fix 2) now very quickly ;-) ... please update to latest solution 2.2

**Comment by walkerjono** [comment]
Awesome, thanks!

**Comment by Triangle333** [comment]
Thanks! Our QA is happy now
