### ISSUE TITLE
Control doesn't show updated content (getAttribute.setValue)

### ISSUE THREAD

**Issue by jellevervloessem** [ChrisMayor/D365RichTextEditor#6]
Hi,

onChange of Field A, we load text from another entity in the content of the RichText-field.
`formContext.getAttribute("meetingminutes").setValue(templateText);`
but since I installed the managed version (and now also v2.4) the D365RichtTextEditor won't show the update text.

Am I missing something? Or is the control not aware of any change?

**Comment by ChrisMayor** [comment]
Hello Jelle,

currently, the control is not aware of any change with setValue (since fixing of the issue: https://github.com/ChrisMayor/D365RichTextEditor/issues/2).

I will try to solve this in the next days.

**Comment by ChrisMayor** [comment]
The way async changes are handled in the PCF Framework is not good. I hope Microsoft will provide a better support for changes and change detection in future versions of the PCF Framework.

I now made some workarounds in the control and I think it works now good for a text control including change detection. So, please upgrade to 2.5 and please let me know if you observe any side effects.

I had a look at some different pcf text controls on Github and haven't seen one with a good solution for this, so either the avoid any change detection (by not calling NotifiyChanged in the control) or don't support setValue in Dynamics (by ignoring updates after initialization of the control),

This Text control offers now both.
