### ISSUE TITLE
Control doesn't become read-only when the form becomes read-only

### ISSUE THREAD

**Issue by markduk** [ChrisMayor/D365RichTextEditor#8]
I am using javascript to change the forms state (Active -> Inactive) or (Inactive -> Active).

```JavaScript
Xrm.WebApi.updateRecord('entity_name', primaryControl.data.entity.getId(), {
    statecode: 2, // Inactive
    statuscode: 2 // Inactive
}).then(() => {
    formContext.data.refresh(true);
});
```

On success I refresh the form, all of the other controls on the page change to the appropriate edit mode (Editable or Read-only) but this control does not.  If I refresh the page using F5 the control then has the correct edit mode.

This is happening in v2.5 (I saw Issue #4 said this was fixed in 2.2 but still seems to be an issue.)

**Comment by ChrisMayor** [comment]
Thank you for opening an issue for this.

I will analyze/fix this in the next days.

**Comment by ChrisMayor** [comment]
It seems that the Read-only flag got broken in V2.5. I fixed this today - Please update to current solution V2.6.

**Comment by markduk** [comment]
Dankeschön Chris, I can confirm that it is working now.
